language: php

php:
  - '7.1'
  - '7.2'

addons:
  apt:
    sources:
      - sourceline: 'ppa:ondrej/php'
    packages:
      - libsodium-dev

before_install:
  - composer self-update

install:
  - if [ "$(phpenv version-name)" = "7.1" ]; then
        pecl install libsodium-1.0.7 ;
    else
        pecl install libsodium ;
    fi
  - composer install

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls

