language: php
sudo: required

php:
  - '7.1'
  - '7.2'

before_install:
  - composer self-update
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -qq update
  - sudo apt-get install -y libsodium-dev

install:
  - if [ "$(phpenv version-name)" = "7.1" ]; then
        pecl install libsodium-1.0.7 ;
    else
        pecl install libsodium ;
    fi
  - composer install

script:
  - composer test

